{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "58463d41-9217-4e3c-9f2e-7fe22d834f9f",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "from sympy import symbols, sympify, lambdify\n",
    "from ipywidgets import interact, FloatRangeSlider, IntSlider, Text, Dropdown, HBox, VBox\n",
    "\n",
    "# 定义复合梯形法函数\n",
    "def trapezoidal_rule(f, a, b, n):\n",
    "    h = (b - a) / n\n",
    "    x = np.linspace(a, b, n + 1)\n",
    "    y = f(x)\n",
    "    integral = h * (0.5 * y[0] + np.sum(y[1:-1]) + 0.5 * y[-1])\n",
    "    return x, y, integral\n",
    "\n",
    "# 定义复合辛普森法函数\n",
    "def simpson_rule(f, a, b, n):\n",
    "    if n % 2 == 1:  # 确保n为偶数\n",
    "        n += 1\n",
    "    h = (b - a) / n\n",
    "    x = np.linspace(a, b, n + 1)\n",
    "    y = f(x)\n",
    "    integral = h / 3 * (y[0] + y[-1] + 4 * np.sum(y[1:-1:2]) + 2 * np.sum(y[2:-2:2]))\n",
    "    return x, y, integral\n",
    "\n",
    "# 绘图函数\n",
    "def plot_integral_approximation(func_str, interval, n, method):\n",
    "    # 解析函数字符串\n",
    "    x = symbols('x')\n",
    "    expr = sympify(func_str)\n",
    "    func = lambdify(x, expr, 'numpy')\n",
    "    \n",
    "    # 复合梯形法或复合辛普森法\n",
    "    a, b = interval\n",
    "    x_approx, y_approx, integral = (trapezoidal_rule if method == 'Trapezoidal' else simpson_rule)(func, a, b, n)\n",
    "    \n",
    "    # 为原函数生成足够密集的x值\n",
    "    x_dense = np.linspace(a, b, 10000)\n",
    "    y_dense = func(x_dense)\n",
    "    \n",
    "    # 绘图\n",
    "    plt.figure(figsize=(10, 6))\n",
    "    plt.plot(x_dense, y_dense, 'r-', label=f'f(x)')  # 原函数用红色实线表示\n",
    "    \n",
    "    if method == 'Simpson':\n",
    "        # 绘制辛普森法的抛物线段\n",
    "        for i in range(0, len(x_approx) - 2, 2):\n",
    "             parabolas = np.array([x_approx[i], x_approx[i+1], x_approx[i+2]])\n",
    "             parabolas_y = np.array([y_approx[i], y_approx[i+1], y_approx[i+2]])\n",
    "             z = np.polyfit(parabolas, parabolas_y, 2)\n",
    "             p = np.poly1d(z)\n",
    "             plt.plot(np.linspace(x_approx[i], x_approx[i+2], 100), p(np.linspace(x_approx[i], x_approx[i+2], 100)), 'b--')\n",
    "             plt.fill_between(np.linspace(x_approx[i], x_approx[i+2], 100), p(np.linspace(x_approx[i], x_approx[i+2], 100)), color='blue', alpha=0.3)\n",
    "    else:\n",
    "        # 逼近多项式用蓝色虚线表示\n",
    "        plt.plot(x_approx, y_approx, 'b--', label=f'{method} Rule (n={n})')  \n",
    "        plt.fill_between(x_approx, y_approx, color='blue', alpha=0.3)  # 填充颜色\n",
    "    \n",
    "    # 标注节点\n",
    "    plt.scatter(x_approx, y_approx, color='green', zorder=5, label='Nodes')  # 使用绿色散点标注节点\n",
    "    \n",
    "    plt.title(f'Integral Approximation using {method} Rule\\nIntegral ≈ {integral:.4f}')\n",
    "    plt.legend()\n",
    "    plt.xlabel('x')\n",
    "    plt.ylabel('y')\n",
    "    plt.grid(True)\n",
    "    plt.show()\n",
    "\n",
    "# 创建交互式控件\n",
    "func_str = Text(value='sin(x)', description='Function:')\n",
    "interval = FloatRangeSlider(value=[0, np.pi], min=-100, max=100, step=0.1, description='Interval:')\n",
    "method = Dropdown(options=['Trapezoidal', 'Simpson'], value='Trapezoidal', description='Method:')\n",
    "\n",
    "# 动态调整节点数控件\n",
    "def update_n_slider(method):\n",
    "    if method == 'Trapezoidal':\n",
    "        n_slider.max = 100\n",
    "        n_slider.step = 1\n",
    "    else:\n",
    "        n_slider.max = 100\n",
    "        n_slider.step = 2\n",
    "        n_slider.value = 2 if n_slider.value % 2 != 0 else n_slider.value\n",
    "\n",
    "n_slider = IntSlider(value=2, min=2, max=100, step=1, description='Nodes:')\n",
    "method.observe(update_n_slider, names='value')\n",
    "\n",
    "# 创建交互式界面\n",
    "controls = VBox([func_str, interval, method, n_slider])\n",
    "interact(plot_integral_approximation, func_str=func_str, interval=interval, n=n_slider, method=method)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
